### ISSUE TITLE
Needs patching for GHC 8.2.2

### ISSUE THREAD

**Issue by spwhitton** [haskell-hvr/token-bucket#7]
Hello,

This library needs some updates to work with recent versions of the 'base' and 'time' libraries, as bundled with GHC 8.2.2.

(Joining stackage (#6) would help with this kind of issue in the future.)

(ping @joeyh)

Thanks.

**Comment by hvr** [comment]
> This library needs some updates to work with recent versions of the 'base' and 'time' libraries, as 
bundled with GHC 8.2.2.

Can you elaborate please? (`token-bucket-0.1.0.1` on Hackage](http://hackage.haskell.org/package/token-bucket-0.1.0.1) works just fine for me with GHC 8.2.2 as well as GHC 8.4.2.

**Comment by clinty** [comment]
We have not incorporated the revisions from https://hackage.haskell.org/package/token-bucket-0.1.0.1/revisions/ as local patches to the source; this was also made more difficult by Hackage being down.

**Comment by spwhitton** [comment]
Sorry for not having checked the situation out more throughly, @hvr, and thank you for your reply.
